# Start from Node base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy entire monorepo into container
COPY . .

# Generate Prisma client in db package
RUN cd packages/db && npx prisma generate

# Move to backend app and install dependencies
WORKDIR /app/apps/backend
RUN npm install

RUN npm run build

# Start the backend server
CMD ["npm", "run", "start"]
