name: Deploy Backend Image

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -f ./docker/Dockerfile.backend \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest \
            ./apps/backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
