name: Frontend CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build frontend image
        run: |
          docker build --pull -f ./docker/Dockerfile.frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Cleanup Docker
        run: docker system prune -af
