name: Frontend CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build frontend
        run: docker build --pull -f ./apps/web/Dockerfile.web -t ${{ secrets.DOCKERHUB_USERNAME }}/web:latest .

      - name: Push web image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/web:latest

      - name: Cleanup Docker
        run: docker system prune -af
